version: '3'
services:
  server:
    build: 
      context: "./server/"
      args:
        - NODE_ENV=development
    volumes:
      - ./server/src:/app/src
    command: npm run start:dev
  client:
    build: 
      context: "./client/"
      args:
        - NODE_ENV=development
    volumes:
      - ./client/src:/app/src:ro
      - /app/node_modules
    command: npm run start
  
volumes:
  images: 