version: '3'

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "user#12345"
      POSTGRES_USER: "user"
      POSTGRES_DB: db
    ports:
      - '5432:5432'
      
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - server
      - client
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  server:
    container_name: server
    build: 
      context: "./server/"
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    container_name: client
    build: 
      context: "./client/"
      dockerfile: Dockerfile
    depends_on:
      - server
    env_file:
      - ./client/.env
    expose: 
      - 3000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db

volumes:
  database: 